version: "4"
services:
  mysql:
    image: mysql:8.3.0
    container_name: go-bookstore-mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./Docker/mysql:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql #my sql file is added to the mydql container#my sql file is added to the mysql container
